### ISSUE TITLE
Add: Mega TV [MZ] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#9361] opened 2024-02-04 12:52 UTC
### Channel Name

Mega TV

### Country

MZ

### City (optional)

Maputo

### Broadcast Area

c/MZ

### Languages

por

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://www.mega.co.mz/

### Logo

https://i.imgur.com/WGwSaAK.jpg

**Comment by Dum4G** [comment] 2024-02-05 11:23
Duplicate of https://iptv-org.github.io/channels/mz/MegaTV

**Closed by Dum4G** 2024-02-05 11:23 UTC
Labels: channels:add, approved
