### ISSUE TITLE
Add: MTV Max

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15047] opened 2024-12-28 21:26 UTC
### Channel Name

MTV Max

### Alternative Names (optional)

MTV Max HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Website (optional)

https://fi.wikipedia.org/wiki/MTV_Max

### Logo

https://img.prod.telkku.com/channel-logos/MTV%20Max%20lightBG.png

**Comment by freearhey** [comment] 2024-12-29 11:47
Please update your request:

- link to the official website is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment] 2024-12-29 12:06
Duplicate of https://iptv-org.github.io/channels/fi/CMoreMax

**Closed by freearhey** 2024-12-29 12:06 UTC
Labels: channels:add, rejected:duplicate
