### ISSUE TITLE
Add: MTV Sub

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15032] opened 2024-12-28 20:35 UTC
### Channel Name

MTV Sub

### Alternative Names (optional)

MTV Sub HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Website (optional)

https://fi.wikipedia.org/wiki/MTV_Sub

### Logo

https://img.prod.telkku.com/channel-logos/MTV_Sub_logo.png

**Comment by freearhey** [comment] 2024-12-29 12:12
Duplicate of https://iptv-org.github.io/channels/fi/Sub

**Closed by freearhey** 2024-12-29 12:12 UTC
Labels: channels:add, rejected:duplicate
