### ISSUE TITLE
Edit: Nazali's HDTV

### ISSUE THREAD

**Issue by Patrick3101** [iptv-org/database#4668] opened 2023-08-12 19:30 UTC
### Channel ID (required)

NazalisHDTV.CG

### Channel Name

Nazali's HDTV

### Country

CG

### Subdivision

CG-BZV

### City

Brazzaville

### Broadcast Area

A/CG-BZV

### Languages

fra

### Categories

general

### NSFW

FALSE

### Launched

2023-02-01

### Website

https://nazalismedia.fr

### Logo

https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=332,fit=crop,q=95/YKbPoklZwxsGljGl/logo-nazalis-final-ii-A852yVLVx0ujW9Wn.png

### Notes

Je souhaiterai que les nouveau changer de mon lien streaming soient pris en charge.

**Comment by freearhey** [comment] 2023-08-12 21:19
Duplicate of #4645

**Closed by freearhey** 2023-08-12 21:19 UTC
Labels: channels:edit
