### ISSUE TITLE
Add: WWUP-DT7

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#14633] opened 2024-12-06 23:24 UTC
### Channel Name

WWUP-DT7

### Network (optional)

Grit

### Owners (optional)

910 Media Group

### Country

US

### Subdivision (optional)

US-MI

### City (optional)

Sault Ste Marie

### Broadcast Area

s/US-MI

### Languages

eng

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://publicfiles.fcc.gov/tv-profile/WWUP-TV

### Logo

https://d229kpbsb5jevy.cloudfront.net/teleup/content/common/logos/channel/logos/grit.png

**Comment by freearhey** [comment] 2024-12-07 13:01
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by ProPontifex** [comment] 2024-12-07 22:18
Fixed

**Comment by BellezaEmporium** [comment] 2024-12-10 19:25
![image](https://github.com/user-attachments/assets/fd5d2dc9-cd08-4aa6-ace5-4ce99dde3439)
No mention of Grit per RabbitEyes, but QVC is in that spot.

**Comment by BellezaEmporium** [comment] 2024-12-10 19:31
One mention I see of WWUP having Grit (twice, which is rather unexpected) is in this : https://en.wikipedia.org/wiki/WWTV

However, even the sources they get their information from is... RabbitEyes. Could be a mistake.

**Comment by ProPontifex** [comment] 2024-12-15 03:20
Exactly...I went with Grit twice.

**Comment by BellezaEmporium** [comment] 2024-12-15 16:36
It was indeed a Wikipedia mistake, both RabbitEars and ChannelMaster both indicate WWTV-DT5 as QVC (instead of Grit). I can confirm the existence of DT7 having Grit : https://www.channelmaster.com/pages/tv-antenna-map-cadillac-mi-49601

I've made the necessary changes with the additional reference to the Wikipedia page. If WWUP is a dupe of WWTV, then this is good to go.

**Comment by BellezaEmporium** [comment] 2024-12-15 16:36
It was indeed a Wikipedia mistake, both RabbitEars and ChannelMaster both indicate WWTV-DT5 as QVC (instead of Grit). I can confirm the existence of DT7 having Grit : https://www.channelmaster.com/pages/tv-antenna-map-cadillac-mi-49601

I've made the necessary changes with the additional reference to the Wikipedia page. If WWUP is a dupe of WWTV, then this is good to go.

**Comment by BellezaEmporium** [comment] 2024-12-15 16:38
Confirmed WWUP is the satellite version of WWTV, with the base in Sault Ste. Marie. LGTM.

**Closed** 2024-12-16 01:18 UTC
Labels: channels:add, approved
