### ISSUE TITLE
Edit: TNT (Mexico)

### ISSUE THREAD

**Issue by VillGas** [iptv-org/database#8520] opened 2023-12-11 23:37 UTC
### Channel ID (required)

TNT.mx

### Channel Name

TNT

### Country

Mexico

### City

Mexico

### Languages

Spanish 

### Categories

Animation

### NSFW

None

### Closed

2025-12-30

**Comment by freearhey** [comment] 2023-12-11 23:40
Duplicate of https://github.com/iptv-org/database/issues/8519

**Closed by freearhey** 2023-12-11 23:40 UTC
Labels: channels:edit
