### ISSUE TITLE
Add: Channel

### ISSUE THREAD

**Issue by Aldair0009** [iptv-org/database#2195] opened 2023-02-02 02:10 UTC
### Channel Name

Channel 5

### Country

Belize

### City (optional)

Belize City

### Broadcast Area

-

### Languages

English

### Categories (optional)

-

### NSFW

FALSE

### Logo

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.facebook.com%2FChannel5BelizeTV%2F&psig=AOvVaw2goR4_rPEcHN8xoK_4D_KR&ust=1675390112517000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCJjF_prh9fwCFQAAAAAdAAAAABAE

**Comment by freearhey** [comment] 2023-02-02 02:28
Duplicate of https://github.com/iptv-org/database/issues/2194

**Closed by freearhey** 2023-02-02 02:28 UTC
