### ISSUE TITLE
Edit: TV5 (Philippines)

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14953] opened 2024-12-25 05:34 UTC
### Channel ID (required)

TV5.ph

### Channel Name

TV5 PH

### Alternative Names

5 Channel

### Network

TV5 Network, Inc.

### Owners

MediaQuest Corporation

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

news; ent

### NSFW

None

### Website

https://tv5.com.ph

**Comment by freearhey** [comment] 2024-12-25 09:17
Duplicate of https://github.com/iptv-org/database/issues/14952

**Closed by freearhey** 2024-12-25 09:17 UTC
Labels: channels:edit
