### ISSUE TITLE
Add: Panorama TV [AL]

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/database#3123] opened 2023-04-08 01:57 UTC
### Channel Name

Panorama TV

### Country

AL

### Broadcast Area

c/AL

### Languages

sqi

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

http://www.panorama.com.al/

### Logo

https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/78/f9/82/78f9821d-cc3d-d581-394d-757e1a6d7d75/source/512x512bb.jpg

**Comment by freearhey** [comment] 2023-04-09 20:49
Duplicate of #2883

**Closed by freearhey** 2023-04-09 20:49 UTC
Labels: channels:add
