### ISSUE TITLE
Add: WCVI-DT1

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#15104] opened 2024-12-31 02:40 UTC
### Channel Name

WCVI-DT1

### Network (optional)

CBS

### Owners (optional)

Lilly Broadcasting

### Country

VI

### City (optional)

Christiansted

### Broadcast Area

c/VI

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1997-05-16

### Website (optional)

https://usvinews.tv/

### Logo

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6d58AVogjfGblwZn2VQtRfZuuvvFgkPFSPCtOUPNCN7ey7aEA0dWnZx4yBiccSzQS_e4&usqp=CAU

**Comment by freearhey** [comment] 2024-12-31 04:17
Duplicate of https://iptv-org.github.io/channels/us/WCVIDT1

**Closed by freearhey** 2024-12-31 04:17 UTC
Labels: channels:add, rejected:duplicate
