### ISSUE TITLE
Add: SPI Lebanon

### ISSUE THREAD

**Issue by saidghzayel** [iptv-org/database#4681] opened 2023-08-14 05:27 UTC
### Channel Name

SPI Lebanon

### Alternative Names (optional)

SPI

### Country

LB

### Broadcast Area

LB-BA

### Languages

ara,arb

### NSFW

FALSE

### Launched (optional)

2020-06-01

### Website (optional)

https://spilebanon.com

### Logo

https://spilebanon.com/img/spi-logo.jpg

### Notes

M3U8 Streaming URL : http://stream.spilebanon.com:1935/live/myStream/playlist.m3u8

**Comment by freearhey** [comment] 2023-08-14 06:15
Duplicate of #4674

**Closed by freearhey** 2023-08-14 06:15 UTC
Labels: channels:add
