### ISSUE TITLE
Edit: Televisiete

### ISSUE THREAD

**Issue by BlueCapped** [iptv-org/database#15022] opened 2024-12-28 01:46 UTC
### Channel ID (required)

Televisiete.gt

### Alternative Names

Canal 7 (Guatemala)

### NSFW

None

**Comment by freearhey** [comment] 2024-12-29 12:17
Please update your request:

- no need to specify the country in the channel alternative name

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment] 2024-12-29 12:19
Duplicate of https://github.com/iptv-org/database/issues/15018

**Closed by freearhey** 2024-12-29 12:19 UTC
Labels: channels:edit, rejected:duplicate
