### ISSUE TITLE
Edit: Lolo TV [LV]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#9456] opened 2024-02-07 19:47 UTC
### Channel ID (required)

LoloTV.lv

### NSFW

None

### Logo

https://imgur.com/hfXoJIY

**Comment by Dum4G** [comment] 2024-02-08 06:48
Duplicate of Pingviins.lv. Thanks for reminding me

**Comment by BellezaEmporium** [comment] 2024-02-08 14:19
Closing, creating another PR for channel removal.

**Closed by BellezaEmporium** 2024-02-08 14:19 UTC
Labels: channels:edit
